// <auto-generated />
namespace DevGeniusFinance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_v12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_v12));
        
        string IMigrationMetadata.Id
        {
            get { return "201807282022403_User_v1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
